(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';function e(){var a=window,b,c;if(a.interstitialAdFrame)return null!==(b=a.interstitialAdFrame)&&void 0!==b?b:null;try{return null!==(c=a.parent.interstitialAdFrame)&&void 0!==c?c:null}catch(d){}return null};function f(a,b=null){a={type:"rewarded",message:a};b&&(a.payload=b);window.parent.postMessage(JSON.stringify(a),"*")};function h(){};function k(a,b){return Array.prototype.filter.call(a,b,void 0)};function m(a){return"string"==typeof a.className?a.className:a.getAttribute&&a.getAttribute("class")||""}function n(a,b){"string"==typeof a.className?a.className=b:a.setAttribute&&a.setAttribute("class",b)}function q(a){a.classList?a=a.classList.contains("visible"):(a=a.classList?a.classList:m(a).match(/\S+/g)||[],a=0<=Array.prototype.indexOf.call(a,"visible",void 0));return a} 
function r(a){a.classList?a.classList.remove("visible"):q(a)&&n(a,k(a.classList?a.classList:m(a).match(/\S+/g)||[],function(b){return"visible"!=b}).join(" "))};var t;a:{var u=(this||self).navigator;if(u){var v=u.userAgent;if(v){t=v;break a}}t=""};(class{constructor(a,b){this.g=b===w?a:""}}).prototype.toString=function(){return this.g.toString()};var w={};function x(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})}function y(a){return a.replace(/(^|[\s]+)([a-z])/g,function(b,c,d){return c+d.toUpperCase()})};var z=-1!=t.indexOf("Opera"),B=-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"),C=-1!=t.indexOf("Gecko")&&!(-1!=t.toLowerCase().indexOf("webkit")&&-1==t.indexOf("Edge"))&&!(-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"))&&-1==t.indexOf("Edge"),D=-1!=t.toLowerCase().indexOf("webkit")&&-1==t.indexOf("Edge");function E(a,b,c){if("string"===typeof b)(b=F(a,b))&&(a.style[b]=c);else for(var d in b){c=a;var p=b[d],l=F(c,d);l&&(c.style[l]=p)}}var G={};function F(a,b){var c=G[b];if(!c){var d=x(b);c=d;void 0===a.style[d]&&(d=(D?"Webkit":C?"Moz":B?"ms":z?"O":null)+y(d),void 0!==a.style[d]&&(c=d));G[b]=c}return c}function H(a,b){a.style.display=b?"":"none"};function I(a){H(a.u,!1);e().disableDismissListeners();J(a);a.B&&a.C.addEventListener("click",a.F);e().addViewListener(()=>{-1!==a.h&&(a.v=setInterval(()=>{a.o||document.hidden||a.s||(a.l++,0<a.h-a.l?J(a):0>=a.h-a.l&&(H(a.H,!1),H(a.C,!1),H(a.u,!0),e().enableDismissListeners(),clearInterval(a.v),a.A&&f("granted",{type:a.K,amount:a.J})))},1E3))})} 
function K(a){const b=.066*a.j+"px";E(document.getElementById("close-confirmation-dialog"),"width",.78*a.j+"px");E(document.getElementById("confirmation-title"),{"font-size":.031*a.g+"px","margin-top":.0375*a.g+"px","margin-left":b,"margin-right":b});E(document.getElementById("confirmation-message"),{"font-size":.025*a.g+"px","margin-bottom":.0375*a.g+"px","margin-top":.0375*a.g+"px","margin-left":b,"margin-right":b});E(document.getElementById("confirmation-buttons"),{"font-size":.0218*a.g+"px","line-height":.05625* 
a.g+"px","margin-right":.0125*a.g+"px","margin-bottom":.0125*a.g+"px"});E(document.getElementById("close-ad-button"),{"padding-left":.044*a.j+"px","padding-right":.044*a.j+"px"});E(document.getElementById("resume-ad-button"),{"padding-left":.044*a.j+"px","padding-right":.044*a.j+"px"})} 
function J(a){var b=a.I;a=a.G.replace("%1$d",(a.h-a.l).toFixed(0));if("textContent"in b)b.textContent=a;else if(3==b.nodeType)b.data=String(a);else if(b.firstChild&&3==b.firstChild.nodeType){for(;b.lastChild!=b.firstChild;)b.removeChild(b.lastChild);b.firstChild.data=String(a)}else{for(var c;c=b.firstChild;)b.removeChild(c);b.appendChild((9==b.nodeType?b:b.ownerDocument||b.document).createTextNode(String(a)))}} 
class L extends h{constructor(){var a=M["countdown-text"],b=parseInt(M["countdown-seconds"],10),c=parseInt(M.width,10),d=parseInt(M.height,10),p="true"===M.rewarded,l="true"===M.is_drx_rewarded_web,Q=M.gam_rewarded_web_reward_type,R=parseInt(M.gam_rewarded_web_reward_amount,10);super();this.I=document.getElementById("count-down-text");this.G=a;this.h=b;this.H=document.getElementById("count-down-container");this.C=document.getElementById("close-button");this.u=document.getElementById("dismiss-button-element"); 
this.D=document.getElementById("dialog-wrapper");this.l=0;this.i=null;this.o=this.s=!1;this.v=0;this.g=Math.max(c,d);this.j=Math.min(c,d);this.B=p;this.A=l;this.K=Q;this.J=R;this.m=g=>{this.o&&(this.o=!1,document.getElementById("resume-ad-button").removeEventListener("click",this.m),document.getElementById("close-ad-button").removeEventListener("click",this.m),r(this.D));"close-ad-button"===g.target.id?(this.i&&this.i.dispatchEvent("confirmationCloseClicked"),e().dismiss(6)):this.i&&this.i.dispatchEvent("confirmationResumeClicked")}; 
this.F=()=>{if(0>=this.h-this.l&&-1!==this.h)e().dismiss(7);else{this.o=!0;this.i&&this.i.dispatchEvent("confirmationDialogueShown");var g=this.D;if(g.classList)g.classList.add("visible");else if(!q(g)){var A=m(g);n(g,A+(0<A.length?" visible":"visible"))}document.getElementById("resume-ad-button").addEventListener("click",this.m);document.getElementById("close-ad-button").addEventListener("click",this.m)}};I(this);this.B&&K(this);this.A&&f("prefetched")}init(a,b){this.i=b;this.h=Math.min(this.h,a)}pauseTimer(){this.s= 
!0}resumeTimer(){this.s=!1}};const N=function(a,b=null){return b&&b.getAttribute("data-jc")===String(a)?b:document.querySelector(`[${"data-jc"}="${a}"]`)}(94,document.currentScript);if(null==N)throw Error("JSC not found 94");var M;const O={},P=N.attributes;for(let a=P.length-1;0<=a;a--){const b=P[a].name;0===b.indexOf("data-jcp-")&&(O[b.substring(9)]=P[a].value)}M=O;window.countdownHandler=new L;}).call(this);
